services:
  - type: web
    name: liberchat
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_GIPHY_API_KEY
        value: GlVGYHkr3WSBnllca54iNt0yFbjz7L65
    healthCheckPath: /
    autoDeploy: true
