name: Build Windows App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install Dependencies
        working-directory: electron
        run: npm install
        
      - name: Build
        working-directory: electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build -- --win nsis:x64
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Liberchat-Windows
          path: electron/dist/*Setup*.exe
