name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Verify Directory Structure
        shell: pwsh
        run: |
          Write-Output "Current directory structure:"
          Get-ChildItem -Recurse
          if (!(Test-Path electron)) {
            Write-Error "electron directory not found"
            exit 1
          }
          
      - name: Install Dependencies
        working-directory: electron
        run: |
          npm ci
          npm list electron electron-builder
          
      - name: Verify Package.json
        working-directory: electron
        shell: pwsh
        run: |
          if (!(Test-Path package.json)) {
            Write-Error "package.json not found"
            exit 1
          }
          Get-Content package.json
          
      - name: Generate Certificate
        working-directory: electron
        shell: bash
        run: |
          openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=Liberchat"
          openssl pkcs12 -export -out cert.pfx -inkey key.pem -in cert.pem -passout pass:liberchat
        
      - name: Build
        working-directory: electron
        env:
          CSC_LINK: cert.pfx
          CSC_KEY_PASSWORD: liberchat
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build process completed"
        
      - name: Verify Build Output
        working-directory: electron
        shell: pwsh
        run: |
          echo "Checking dist directory..."
          if (!(Test-Path dist)) {
            Write-Error "dist directory not found"
            exit 1
          }
          echo "Listing dist directory contents:"
          Get-ChildItem dist -Recurse
          if (!(Test-Path "dist/*Setup*.exe")) {
            Write-Error "No installer found in dist directory"
            exit 1
          }
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "electron/dist/*Setup*.exe"
          draft: false
          prerelease: false
          body: |
            # Liberchat ${{ github.ref_name }}

            Nouvelle version de Liberchat pour Windows !

            ## Installation
            1. Téléchargez l'installateur (.exe)
            2. Double-cliquez sur l'installateur
            3. Suivez les instructions d'installation
            
            ## Version
            ${{ github.ref_name }}
            
            ## Date de publication
            ${{ format(github.event.repository.updated_at, 'DD/MM/YYYY') }}
            
            ## Notes de version
            - Nouvelle version avec installateur Windows
            - Interface utilisateur améliorée
            - Corrections de bugs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        working-directory: electron
        shell: pwsh
        run: |
          Remove-Item -Path cert.pfx -Force -ErrorAction SilentlyContinue
          Remove-Item -Path key.pem -Force -ErrorAction SilentlyContinue
          Remove-Item -Path cert.pem -Force -ErrorAction SilentlyContinue

