name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install Dependencies
        working-directory: electron
        run: npm install
        
      - name: Create Certificate
        working-directory: electron
        run: |
          $cert = New-SelfSignedCertificate -DnsName "Liberchat" -Type CodeSigning -CertStoreLocation Cert:\CurrentUser\My
          $password = ConvertTo-SecureString -String "${{ secrets.WINDOWS_PFX_PASSWORD }}" -Force -AsPlainText
          $path = "cert.pfx"
          Export-PfxCertificate -Cert "Cert:\CurrentUser\My\$($cert.Thumbprint)" -FilePath $path -Password $password
        shell: powershell
        
      - name: Build
        working-directory: electron
        run: npm run build
        env:
          WINDOWS_PFX_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}
        
      - name: List Files
        working-directory: electron/dist
        run: dir
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: electron/dist/*.exe
          body: |
            # Liberchat ${{ github.ref_name }}

            Nouvelle version de Liberchat pour Windows !

            ## Nouveautés
            - Installation complète avec logo
            - Raccourcis bureau et menu démarrer
            - Désinstallation propre
            - Support multiplateforme (Windows, Web)

            ## Installation
            Téléchargez et lancez Liberchat-Setup.exe pour installer Liberchat sur Windows.
