name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install Dependencies
        working-directory: electron
        run: npm install
        
      - name: Build
        working-directory: electron
        run: npm run build
        
      - name: List Files
        working-directory: electron/dist
        run: dir
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: electron/dist/*.exe
          body: |
            # Liberchat ${{ github.ref_name }}

            Nouvelle version de Liberchat pour Windows !

            ## Installation
            Téléchargez et lancez l'installateur pour installer Liberchat sur Windows.
